// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoqvNpNFH-04O6MSZmi0nfXM1S0sryI4Q',
    appId: '1:946414910359:web:6e5118ed57e0a0ea96e2d2',
    messagingSenderId: '946414910359',
    projectId: 'store-e438e',
    authDomain: 'store-e438e.firebaseapp.com',
    storageBucket: 'store-e438e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVZwJi3NRVOwGk-ttp_1bdy3QLPfX5bfE',
    appId: '1:946414910359:android:8f34b06d8ab6eb9396e2d2',
    messagingSenderId: '946414910359',
    projectId: 'store-e438e',
    storageBucket: 'store-e438e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk04c9OBX4FFh6fYCIg1z_M3CnPCx-FYY',
    appId: '1:946414910359:ios:967f946cf4c13ca496e2d2',
    messagingSenderId: '946414910359',
    projectId: 'store-e438e',
    storageBucket: 'store-e438e.firebasestorage.app',
    iosBundleId: 'com.example.chatat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk04c9OBX4FFh6fYCIg1z_M3CnPCx-FYY',
    appId: '1:946414910359:ios:967f946cf4c13ca496e2d2',
    messagingSenderId: '946414910359',
    projectId: 'store-e438e',
    storageBucket: 'store-e438e.firebasestorage.app',
    iosBundleId: 'com.example.chatat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoqvNpNFH-04O6MSZmi0nfXM1S0sryI4Q',
    appId: '1:946414910359:web:67d69f082d336acf96e2d2',
    messagingSenderId: '946414910359',
    projectId: 'store-e438e',
    authDomain: 'store-e438e.firebaseapp.com',
    storageBucket: 'store-e438e.firebasestorage.app',
  );

}